version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__DEBUG=false
    volumes:
      - qdrant_storage:/qdrant/storage

  rag_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_api
    restart: unless-stopped
    environment:
      - PORT=8000
      # Add your own env here (e.g. model names, API keys, Qdrant URL)
      - QDRANT_URL=http://qdrant:6333
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - qdrant

volumes:
  qdrant_storage:
    driver: local


