services:
  ollama:
    build:
      context: .
      dockerfile: Ollama.Dockerfile
      args:
        - OLLAMA_DEFAULT_MODEL=qwen2.5:3b
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_NUM_PARALLEL=1
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 10

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__DEBUG=false
    volumes:
      - qdrant_storage:/qdrant/storage

  rag_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_api
    restart: unless-stopped
    environment:
      - PORT=8000
      # Add your own env here (e.g. model names, API keys, Qdrant URL)
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_HOST=http://ollama:11434
      - HF_HOME=/models/hf
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - hf_cache:/models/hf
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      qdrant:
        condition: service_started
      ollama:
        condition: service_started

volumes:
  qdrant_storage:
    driver: local
  hf_cache:
    driver: local


